// Generated by CoffeeScript 1.4.0
(function() {
  var app, counter, express, http, io, path, qrCode, server;

  express = require('express');

  http = require('http');

  path = require('path');

  app = express();

  app.configure(function() {
    app.set('port', process.env.PORT || 3000);
    return app.use(express["static"](path.join(__dirname, 'public')));
  });

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  server = require('http').createServer(app).listen(app.get('port'), function() {
    return console.log("Express server listening on port " + app.get('port'));
  });

  counter = 0;

  qrCode = require('qrcode-npm');

  io = require('socket.io').listen(server, {
    'log level': 1
  });

  io.sockets.on('connection', function(socket) {
    var imgTag, qr, tableTag, url;
    counter++;
    if (counter === 2) {
      socket.broadcast.json.emit('connection_complete', {
        connection: 'ok'
      });
      counter = 0;
    }
    qr = qrCode.qrcode(4, 'M');
    url = 'http://localhost:3000/controller.html';
    qr.addData(url);
    qr.make();
    imgTag = qr.createImgTag(4);
    tableTag = qr.createTableTag(4);
    socket.emit('qrcode', {
      img: imgTag,
      url: url
    });
    return socket.on('direction', function(data) {
      return socket.broadcast.json.emit('direction', {
        direction: data.direction
      });
    });
  });

}).call(this);
